version: 0.2

#TODO: Move all constatns to environment variables
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $REGION)
      - pip install -r src/requirements.txt
      - bash src/setup.sh $pytorch
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - python src/main.py --buildspec pytorch/buildspec-1-4.yml --framework pytorch --image_types training --device_types cpu --py_versions py3
  post_build:
    commands:
      - echo Build step finished on `date`
artifacts:
  files:
    - $HOME/test_type_images.json
  name: DLC_IMAGES_JSON
  discard-paths: yes

